language: go

# Docker is required for fuzzit regression tests
services:
  - docker

os:
  - linux
  - osx
go:
  - tip
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x

matrix:
  allow_failures:
    - tip
  fast_finish: true

before_install:
  - go get -t -v ./...
  # - go get -v golang.org/x/tools/cmd/goimports

jobs:
  include:
    - stage: test
      script:
        # TODO(@kirilldanshin)
        # - test -z "$(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*"))"
        # build test for supported platforms
        - GOOS=linux go build
        - GOOS=darwin go build
        - GOOS=freebsd go build
        - GOOS=windows go build
        - GOARCH=386 go build

        # run tests on a standard platform
        - go test -v ./...

        # run tests with the race detector as well
        - go test -race -v ./...
    - stage: fuzzit.dev (fuzzing)
      if: branch = master AND type IN (push)
      os:
        - linux
      go:
        - 1.12.x
      script:
        - ./fuzzit.sh fuzzing
    - stage: fuzzit.dev (regression)
      os:
        - linux
      go:
        - 1.12.x
      script:
        - ./fuzzit.sh local-regression

